### ISSUE TITLE
Really good! Please write some articles to help it get more traction!

### ISSUE THREAD

**Issue by trusktr** [apioo/typeschema#12]
:)

**Comment by chriskapp** [comment]
Hi @trusktr , thanks for the great feedback. Indeed articles and in general marketing is currently not our strength :) but we are really confident that in the long term a project like TypeSchema is needed to solve the code generation problems with JsonSchema and also regarding OpenAPI. We have also the idea to submit TypeSchema to https://spec.openapis.org/registry/alternative-schema/ so that we can use it directly inside OpenAPI. Regarding articles do you have a specific place where you think this would reach many users?
