### ISSUE TITLE
What does the error "Property must not contain a nested struct" mean?

### ISSUE THREAD

**Issue by trusktr** [apioo/typeschema#13]
I got the error `Property must not contain a nested struct`, but not sure what it means.

Love the project, btw. JSON Schema tooling is so bad. TypeSchema is wonderful.

**Comment by trusktr** [comment]
Idea: maybe the online generator and migrator can show a line number to help pin point issues.

**Comment by chriskapp** [comment]
@trusktr regarding the error, so this means basically that you can not have a nested object i.e.

```json
{
  "definitions": {
    "my_object": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "object",
          "properties": {
            "bar": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

In TypeSchema you would need to rewrite this:

```json
{
  "definitions": {
    "my_object_child": {
      "type": "object",
      "properties": {
        "bar": {
          "type": "string"
        }
      }
    },
    "my_object": {
      "type": "object"
      "properties": {
        "foo": {
          "$ref": "my_object_child"
        }
      }
    }
  }
}
```

This has the great advantage that we have an identifier for the nested object and thus we can generate i.e. a class representation of this object.

Regarding the idea, this would be indeed useful to detect problems. Maybe we can also include a JSON Path pointing to the nested object since line numbers are not always useful at JSON i.e. if you JSON payload does not contain a new line, but I will take a look and see how we can improve the error message.

So great that you like the project and we think also that there is some great potential to improve the current ecosystem.

**Comment by trusktr** [comment]
Ah, got it. Thanks!

> So great that you like the project and we think also that there is some great potential to improve the current ecosystem.

Yeah, it's really good. I tried every JSONSchema-to-TypeScript tool I could find, and could not end up with anything useful.

With TypeSchema, it either shows errors that need to be fixed, or finally outputs excellent code. 👍
