### ISSUE TITLE
Protobuf serialization doesn't have stable numbers

### ISSUE THREAD

**Issue by tvh** [apioo/typeschema#20]
When serializing to protobuf, the binary protocol is not generated in a migration-safe manner. Say I do the following specs:

**V1:**
typeschema:
```.json
{
  "definitions": {
    "Student": {
      "type": "struct",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        }
      }
    }
  },
  "root": "Student"
}
```
protobuf:
```.proto
message Student {
    optional string firstName = 1 [json_name="firstName"];
    optional int64 age = 2 [json_name="age"];
}
```

**V2**
typeschema:
```
{
  "definitions": {
    "Student": {
      "type": "struct",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        }
      }
    }
  },
  "root": "Student"
}
```
protobuf:
```.proto
message Student {
    optional string firstName = 1 [json_name="firstName"];
    optional string lastName = 2 [json_name="lastName"];
    optional int64 age = 3 [json_name="age"];
}
```

Now the `age` field change it's name _and_ type, breaking the binary protocol.

**Comment by chriskapp** [comment]
Hi @tvh thanks for the feedback, I am not sure whether we can solve this at our generator since the generator only has information about the current specification, it does not know, whether there is a previous version where the age property was placed at a different position. The only solution which I could image would be to build the integer based on the property name, through this the number would be stable and only changes if you also change the property name, maybe this would be better?

**Comment by tvh** [comment]
I think the only correct solution would be to add the tag to the typeschema model.

Deriving the number from the field name may work for most objects but will sometimes create conflicts. You only have ~500k numbers to choose from (see https://protobuf.dev/programming-guides/proto2/#assigning). That means collisions are relatively unlikely but far from impossible.

**Comment by chriskapp** [comment]
@tvh thanks for the hint, in general we try to not add language specific properties to the specification since the use case of TypeSchema is basically to write the spec once and then generate for different target languages, otherwise you could also simply use protobuf directly. But maybe the idea is not too bad to generate the number based on the property name, since the current behaviour is not optimal, like you pointed out.

**Comment by chriskapp** [comment]
I have also just added an implementation which be available at the next release, for example a struct would then look like this (from our tests cases) s.
![image](https://github.com/user-attachments/assets/78b77d6a-a194-48f0-bf5a-4a52f29aa141)

Since the key of the map is also inherently unique we are safe that also the number is unique. In our case we simply build the sum of each ascii character. I have also added a check to exclude the range 19,000 to 19,999 in case a user has really long property names.

**Comment by tvh** [comment]
>In our case we simply build the sum of each ascii character.

I do see that that is a simple implementation but extremely brittle. Take `note` and `tone` for example, they would have the same value. I think the only way to have this be reasonably safe is to use a proper hash-function that maps the name to a number.

**Comment by chriskapp** [comment]
@tvh this is indeed true, the problem is, we can use max 536_870_911 as int. If we use the smallest hash function md5 which gives us 32 hex chars, and we simply use each 4 bit of each hex char we get a 128 bit int which is always larger then 536_870_911, for larger hash functions it gets worse.

With 536_870_911 we can basically use only 29 bits, this means we can only use the first 7 chars of the hash string so that we use 28 bits. This could somehow work but has of course collision problems. But since 7 digits are also the default at git it maybe indeed enough for these property names.

**Comment by tvh** [comment]
@chriskapp Yes this is exactly what I was saying. I just crunched the numbers using https://instacalc.com/28845 for 1000 properties:
![Screenshot 2024-11-17 at 21 03 51](https://github.com/user-attachments/assets/907e3e53-96e6-428e-b89d-97404aa56d78)

I think 0.01% chance of a collision for 1000 properties is pretty good. But it might be good to error out if a collision occurred.
